services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: kindler
      POSTGRES_PASSWORD: kindler
      POSTGRES_DB: kindler
    ports:
      - "5432:5432"
    volumes:
      - kindler-postgres-data:/var/lib/postgresql/data

volumes:
  kindler-postgres-data:
